### ISSUE TITLE
Please respect what you do before sending us to proof read

### ISSUE THREAD

**Issue by nicktsui61** [w3c/WCAG21-zh#1]
Not sure how you guys work this out. Apparently most of them were google translated, it is really difficult to read in Chinese, how would you expect others to use this as guideline?

**Comment by ruoxiran** [comment]
This document is a Candidate Authorized Translation (CAT) document provided by Zhejiang University. Please submit any unreasonable part to Github or send email to public-auth-trans-zh@w3.org. We welcome comments from you or your organization.

**Comment by hbwhzk** [comment]
it is unreadable, google translated?

**Comment by ruoxiran** [comment]
Please submit any unreasonable part to Github or send an email to [LTO(Zhejiang University) and stakeholders](https://lists.w3.org/Archives/Public/w3c-translators/2018AprJun/0012.html) with cc public-auth-trans-zh@w3.org. We welcome comments from you or your organization. Any issue could be fixed in errata.
